services:

  hz:
    image: hazelcast/hazelcast:latest
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
    ports:
      - "5701:5701"
    volumes:
      - ".:/project"
    networks:
      - hazelcast

  mc:
    image: hazelcast/management-center:latest
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast

networks:
  hazelcast:
  